version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "demo-website-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ndc29ph3xaqi"
s3_prefix = "demo-website-backend"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
